-- MySQL Script generated by MySQL Workbench
-- Mon Feb 26 17:21:47 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema chimbiladb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `chimbiladb` ;

-- -----------------------------------------------------
-- Schema chimbiladb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chimbiladb` DEFAULT CHARACTER SET latin1 ;
SHOW WARNINGS;
USE `chimbiladb` ;

-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuario` (
  `id` INT(6) UNSIGNED NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido` VARCHAR(30) NOT NULL,
  `nickname` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` CHAR(41) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `email` ON `usuario` (`email` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `nickname_UNIQUE` ON `usuario` (`nickname` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `audio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `audio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `audio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `ruta` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tipo_etiqueta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipo_etiqueta` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tipo_etiqueta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `etiqueta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etiqueta` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `etiqueta` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `tipo_etiqueta_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tipo_etiqueta_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `anotacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anotacion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `anotacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT(6) UNSIGNED NOT NULL,
  `audio_id` INT NOT NULL,
  `etiqueta_id` INT NOT NULL,
  `tiempo_ini` TIME(5) NULL,
  `tiempo_fin` TIME(5) NULL,
  PRIMARY KEY (`id`, `usuario_id`, `audio_id`, `etiqueta_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `coleccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coleccion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `coleccion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_user_id` INT(6) UNSIGNED NOT NULL,
  `audio_id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `users_user_id`, `audio_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jerarquia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jerarquia` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jerarquia` (
  `id` INT NOT NULL,
  `jerarquia_id` INT NOT NULL,
  `coleccion_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
